### PR TITLE
Duplicate date bugfix

### PR DESCRIPTION
**Pull request by eddierubeiz**
This is a potential fix for #1049 .

Here's what I think is going on:

1) The generic work indexer is not deduplicating date objects before indexing them, as it does for some of the other fields it handles. This leads to duplicates in the SOLR field date_of_work_json_ssm .

2) The way the front-end display handled dates until a couple weeks ago masked this problem by deduplicating the date_of_work_json_ssm items at display time. ( I haven't investigated quite how yet.)

3) When [I changed the way front-end dates were displayed a couple weeks ago](https://github.com/sciencehistory/chf-sufia/commit/2556ae9cc3154025772a76c8d94ed4d4037c9d12), I used the data in date_of_work_json_ssm directly, thus exposing the problem described in 1).

I feel the best way to fix this problem is to modify the generic work indexer, which this PR does. My sense is that fixing this problem lower in the stack makes more sense, as duplicate dates in the date_of_work_json_ssm index could lead to more trouble down the line.

The data in Fedora doesn't appear to contain these duplicates, so, assuming we go this route, a reindex of the items edited since March 20th ( [when field date_of_work_json_ssm was introduced](https://github.com/sciencehistory/chf-sufia/commit/5db10bb75030c9c3ab0a419bfd01b5586375d4b5) ) should fix the problem. We could also run a full reindex, of course.

Quick note: I haven't yet made any further changes to date display in this PR, just to reduce confusion. (I did see your note about it in  issue 1049, @jrochkind , and of course I can easily make that change -- it's just I'd rather deal with this one first).

Also -- I added a regression test for this to the new work feature test.

To run *just* the feature test and then examine the solr field in dev, you might want to try a variation on the following:

```
./bin/rspec spec/features/new_work_feature_spec.rb
curl -vs http://localhost:8985/solr/hydra-test/select?indent=on  2>&1 | grep -5 2010
```

Hope all this makes sense -- let me know how yous feel.

### CODE REVIEW

**Comment by jrochkind** [comment]
That makes sense, but I wonder how the duplicates end up in there in the first place -- we shouldn't really have duplicates in fedora _either_.  It sounds like maybe every time you press 'save', it duplicates all your dates?  Which is not good. 

We can/should definitely de-dup on indexing at least, and can deploy that right away, but maybe make another ticket for ourselves to figure out why the dates the indexer has as input are duplicated in the first place?  Are they duplicated in fedora, or just given to the indexer duplicated somehow, or what?  Are you interested in looking into that?

It also might not be unreasonable to say "it's the stack, it's always gonna have bugs, the best we can do is work around them, rather than spend all our time hunting them." That makes me sad, but I've had to do it before sometimes.

**Comment by jrochkind** [comment]
PS: We can reindex _just works_ with `./bin/rake chf:reindex_works` on a `jobs` server. It takes 1-2 hours. Short enough that it's not worth trying to reindex just things that have changed since X date.

**Comment by eddierubeiz** [comment]
* No, it appears the duplication is not happening in Fedora. It seems there's a bug between the work object and the indexer. I need to double-check that.

* Totally agree it's worth answering the question about where these duplicates are coming from. I'd like to be able to remove the dedupe function from the works indexer entirely. Yes, let's make another ticket -- and I'm happy to work on that ticket.

* As far as what currently gets duplicated, it appears to be the most recently added date only.

**Comment by jrochkind** [comment]
Weird. It honestly might not be worth tracking down, it's just "the stack", de-duping in indexing may be sufficient. I have no idea, it's hard to know when to say when with this stack -- esp when we're running on an old version anyway, it may be different in newer ones, and the current one (we don't use yet) is about to be replaced by yet ANOTHER new one that will have possibly entirely different implementation. 

I'm going to make a commit to add a comment explaining it's mysterious to us why it needs de-duping, and then merge and deploy. 

Just curious -- did you confirm your regression test _failed_ without the fix, it really is a regression test?

And after I merge, do you want to do the reindex, so you know how to do it?

**Comment by eddierubeiz** [comment]
* Sounds good.
* So glad you asked re: the test. I wrote the failing test first, because they drummed TDD into our heads in Portland, and I was like - why the hell not.
* Yeah, happy to reindex. I've done it in dev a couple times. I would like to try it on staging first, assuming we can push this fix to staging, just to double-check that it fixes a few test items.

**Pull request merged**
