### PR TITLE
Use postgres in dev and test, instead of sqlite3

### PR DESCRIPTION
**Pull request by jrochkind**
Be more consistent with prod, and sqlite3 has problems with lots of concurrent access sometimes, which sufia ingest can do.

### CODE REVIEW

**Comment by jrochkind** [comment]
Closes #1084

**Comment by jrochkind** [comment]
@eddierubeiz you wanna try it out on this branch before we merge, to make sure it works as smoothly for you as it is for me, and we're not missing anything? No rush.

**Comment by eddierubeiz** [comment]
I'm already doing just that ...

**Comment by eddierubeiz** [comment]
Yup - works great!

**Comment by jrochkind** [comment]
ok, if you feel ready to deal with it, merge whenever!

**Pull request merged**
