### PR TITLE
Update label before index

### PR DESCRIPTION
**Pull request by eddierubeiz**
Here's a naive attempt to fix https://github.com/sciencehistory/chf-sufia/issues/428. Mostly submitting this as an exercise; I don't claim to know exactly what I'm doing.

### CODE REVIEW

**Comment by jrochkind** [comment]
(Nice job figuring out a solution!)

**Comment by jrochkind** [comment]
It occurs to me that:

1. A comment by that one-liner pointing to the URL for this issue might be good, cause it's mysterious from the code what it is or why it matters. 

2. An automated test would be great. I'm not a total stickler for automated tests, especially when they are painful to do in a given situation and especially when the thing tested is about fighting with sufia, but maybe it would be a good learning experience?   If so, I might try to do it as a front-end test, modelled after this one (although this one only tests creating new work, not editing an existing one). https://github.com/sciencehistory/chf-sufia/blob/master/spec/features/new_work_feature_spec.rb

**Comment by eddierubeiz** [comment]
Good call. I ended up modifying and extending the test you mention in #2 rather than splitting off a new test, since the existing test functions perfectly as the setup for the new test I need. I'm totally open to splitting it off into its own separate test, which would be more elegant but (I suspect) somewhat slower. But it works great as a regression test for bug 428. Thanks for the pointers!

**Comment by eddierubeiz** [comment]
Oh - and here's more or less how I figured this out:

I went back and forth editing the inscriptions between these two URLS
```
	1) :3000/works/work_id
	2) :3000/concern/generic_works/work_id/edit
```

and simultaneously monitored the following 3 URLs by using watch and curl commands:
```
	3) :8080/rest/dev/xx/xx/xx/xx/work_id
	4) :8080/rest/dev/xx/xx/xx/xx/inscription_id
	5) :8983/solr/hydra-development/get?id=work_id
```

Once I figured that URL 1) was getting its data from Fedora, but 2) was getting its data from SOLR, I tweaked the indexing function inside the generic_work controller so as to make sure the inscription label was being updated prior to indexing. There may well be a better place to do this (perhaps in the indexer class for inscriptions) but this seemed to do the trick with minimal fuss.

**Comment by jrochkind** [comment]
@eddierubeiz Makes sense, solr vs fedora issues are a frequent pain, and in my experience there's rarely a "better" place to fix em than whatever hack works, so I prob would have done what you did!

**Pull request merged**
